### ISSUE TITLE
--verbose or --quiet flag

### ISSUE THREAD

**Issue by rizowski** [davidraviv/gh-clean-branches#14]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a smaller output of the command. Listing out the local and remote branches are nice for debugging and seeing what is available. However, having a smaller print output could streamline the user experience.

**Describe the solution you'd like**
Either have a `--verbose` or a `--quiet` flag. `--verbose` would enable the verbose logging. While `--quiet` would opt into being quiet.

**Comment by davidraviv** [comment]
Thanks for the suggestion and the PRs, I'll review it.
