### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by waldyrious** [davidraviv/gh-clean-branches#2]
Installing this extension seems to work:

```console
❯❯❯ gh extension install davidraviv/gh-clean-branches 
Cloning into '/home/waldyrious/.local/share/gh/extensions/gh-clean-branches'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 31 (delta 10), reused 15 (delta 5), pack-reused 0
Receiving objects: 100% (31/31), 6.65 KiB | 3.32 MiB/s, done.
Resolving deltas: 100% (10/10), done.
```

...but actually using it produces an error:

```console
❯❯❯ gh clean-branches
failed to run extension: fork/exec /home/waldyrious/.local/share/gh/extensions/gh-clean-branches/gh-clean-branches: no such file or directory❯❯❯ 
```

If it helps, I'm on Ubuntu 20.04.3 LTS, using gh version 2.0.0.

**Comment by davidraviv** [comment]
Thanks, @waldyrious for the research and contribution!
I'll take a look at the PR.
Most of the `zsh` specific commands that require conversion to `bash` are in the conditions and array handling. I'll try to work on that against the [shellcheck](https://www.shellcheck.net/) when I'll have some free time.

**Comment by tktcorporation** [comment]
I got the same error in my env.
but I tried after installing `zsh` shell, it worked fine.

Thank you!
```fish
> gh clean-branches --dry-run
failed to run extension: fork/exec /home/tkt/.local/share/gh/extensions/gh-clean-branches/gh-clean-branches: no such file or directory

> /bin/zsh
/bin/zsh: command not found

> sudo apt install zsh
...

> 
gh clean-branches
[clean-branches] -> [clean-branches]
Sync branches
Checking out master
M	src/handler/model/speaker.rs
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling master
Already up to date.
Local branches:
   ...
Remote branches:
   ...
Local branches with missing upstream:
   ...
Deleting branch:     bug/18/help
...
Deleting branch:     pr-action
error: The branch 'pr-action' is not fully merged.
If you are sure you want to delete it, run 'git branch -D pr-action'.
❌  Could not delete pr-action
Try manually: git branch -D pr-action
Deleting branch:     test
Deleted branch test (was fb3dff1b2933).

Done
```

**Comment by davidraviv** [comment]
Closing this issue as the script is working once the dependencies are met.

**Comment by waldyrious** [comment]
I find it a bit excessive to require someone to change their shell in order to use a tool, and wouldn't consider that a dependency in the usual sense of the word, but of course it's your decision to make. I hope you will eventually be able to make the script portable across different shells.

**Comment by davidraviv** [comment]
The `zsh` _is_ a dependency, it is not required to use it as the default shell, just for it to be installed. (meaning, you can install it and keep using `bash` as your shell)

I agree that `bash` is more popular than `zsh`. I spent some time learning how to convert the script but I figured out that I won't have the time for it... I'm open to PRs if someone wants to take it. 

To install `zsh` (in addition to `bash`):
On Ubuntu:
```bash
sudo apt install zsh
```
On old Macs (New macs deliver now with `zsh` as their default shell):
```bash
brew install zsh
```

**Comment by waldyrious** [comment]
> The zsh is a dependency, it is not required to use it as the default shell, just for it to be installed. (meaning, you can install it and keep using bash as your shell)

Oh, cool, thanks for clarifying!
