### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by heaths** [davidraviv/gh-clean-branches#23]
**Describe the bug**
Running the extension just after installing it shows,

```
--: line 1: C:\Users\heaths\AppData\Local\GitHub CLI\extensions\gh-clean-branches\gh-clean-branches: cannot execute: required file not found
```

This appears to be because it requires zsh instead of bash, the latter of which is installed with git and accessible to any callers.

**To Reproduce**
1. Install it this extension on Windows.
2. Just run it.

**Expected behavior**
Passing with `--dry-run` should show me watch branches I can delete.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] 11

**Additional context**
I wrote a GitHub CLI extension using script a while back using bash and can repro this same error if I just change the shebang to require zsh.

**Comment by davidraviv** [comment]
Hi @heaths,
Thanks for trying the extension, and for investing the time in trying to improve it.
Unfortunately, the extension depends on zsh as mentioned.
There was a great work done by @ndom91 in [this PR](https://github.com/davidraviv/gh-clean-branches/pull/18) to refactor the code to bash, but it didn't pass tests yet.
